"""empty message

Revision ID: 896cb26ab099
Revises: e97f657fc4d7
Create Date: 2017-09-01 13:29:15.775000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896cb26ab099'
down_revision = 'e97f657fc4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_filename', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('image_url', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_url')
    op.drop_column('user', 'image_filename')
    # ### end Alembic commands ###
