"""empty message

Revision ID: b49e33e5e074
Revises: 896cb26ab099
Create Date: 2017-09-01 19:36:19.748000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49e33e5e074'
down_revision = '896cb26ab099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('store_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_city_name'), 'user', ['city_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_city_name'), table_name='user')
    op.drop_column('user', 'store_number')
    op.drop_column('user', 'city_name')
    # ### end Alembic commands ###
