"""empty message

Revision ID: e97f657fc4d7
Revises: 4204bc0daf51
Create Date: 2017-09-01 13:00:16.322000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97f657fc4d7'
down_revision = '4204bc0daf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('business_location1', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('business_name1', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('contact_number1', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('product_description1', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('search_tags', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_business_location1'), 'user', ['business_location1'], unique=False)
    op.create_index(op.f('ix_user_business_name1'), 'user', ['business_name1'], unique=False)
    op.create_index(op.f('ix_user_contact_number1'), 'user', ['contact_number1'], unique=False)
    op.create_index(op.f('ix_user_product_description1'), 'user', ['product_description1'], unique=False)
    op.create_index(op.f('ix_user_search_tags'), 'user', ['search_tags'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_search_tags'), table_name='user')
    op.drop_index(op.f('ix_user_product_description1'), table_name='user')
    op.drop_index(op.f('ix_user_contact_number1'), table_name='user')
    op.drop_index(op.f('ix_user_business_name1'), table_name='user')
    op.drop_index(op.f('ix_user_business_location1'), table_name='user')
    op.drop_column('user', 'search_tags')
    op.drop_column('user', 'product_description1')
    op.drop_column('user', 'contact_number1')
    op.drop_column('user', 'business_name1')
    op.drop_column('user', 'business_location1')
    # ### end Alembic commands ###
